version: '3.9'

services:
  
  spring_app:
    container_name: spring_app
    image: spring_app:1.0.0
    build: .
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=jdbc:postgresql://postgres_db:5432/computingProjectDB
      - DATABASE_USERNAME=root
      - DATABASE_PASSWORD=root
    depends_on:
      - postgres_db

  postgres_db:
    container_name: postgres_db
    image: postgres:12
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: computingProjectDB
    